version: '3'

services:
  web:
    container_name: reactions_api
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn reactions_api.main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --reload-dir /app/reactions_api --reload-dir /app/tests --log-level debug
      "
    volumes:
      - .:/app
    ports:
      - 8000:8000